language: node_js
node_js:
- stable
services:
- mongodb
deploy:
  provider: gae
  keyfile: otot-task-b-290214-11a462371441.json
  project: otot-task-b-290214
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_87a5c607730b_key -iv $encrypted_87a5c607730b_iv
  -in otot-task-b-290214-11a462371441.json.enc -out otot-task-b-290214-11a462371441.json
  -d
